## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
node.name: logstash
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs